// OnZVoIP - reports the local player's live position to the OnZVoIP relay,
// so it can be broadcast to other players for proximity voice chat.
// Speaks the same protocol as ../tools/simulate-positions.js: one line of
// JSON per position update, newline-delimited, over a raw TCP socket (no
// extra plugin dependency needed — Net::Socket is available out of the box).
//
// Split across files (OpenPlanet compiles every .as file in the plugin
// folder together as one module, so no includes are needed): Main.as (state
// + main loop), Network.as (relay connection/protocol), Interface.as (ImGui
// window + menu), GameState.as (reading player/server info from the game),
// Strings.as (JSON/Trackmania string helpers), Settings.as (user-configurable
// options).

const int SEND_INTERVAL_MS = 200;
const int RECONNECT_INTERVAL_MS = 2000;
const int DIAG_INTERVAL_MS = 3000;
// Refresh the nonce before the relay's 12-minute TTL expires.
const int NONCE_REFRESH_MS = 9 * 60 * 1000;
// While a secret keeps failing, retry the HTTPS token exchange at most this
// often instead of every RECONNECT_INTERVAL_MS — the TCP socket still cycles
// (harmless), but /tcp-auth stops getting hammered while the player figures
// out the right value. A changed secret retries immediately regardless.
const int AUTH_RETRY_BACKOFF_MS = 10000;

Net::Socket@ g_socket = null;
int64 g_lastSendAt = 0;
int64 g_lastConnectAttemptAt = 0;
int64 g_lastDiagAt = 0;
bool g_loggedConnected = false;
bool g_authSent = false;
// Set when the relay rejects our auth (wrong/missing secret) so the widget
// can tell the player "this relay needs a token" instead of just showing
// "connecting..." forever.
bool g_authFailed = false;
// The secret and timestamp of the last failed auth attempt, so a still-wrong
// secret doesn't retry the HTTPS token exchange every reconnect — see
// AUTH_RETRY_BACKOFF_MS. Editing the secret field resets g_authFailed
// (Interface.as), which bypasses this and retries right away.
string g_lastAuthFailSecret = "";
int64 g_lastAuthFailAt = 0;

// One-time nonce generated by the plugin, sent to the relay over TCP and
// embedded in the "Copy URL" link. The relay exchanges it for a JWT already
// bound to the right room, so the player never has to type a login in.
string g_nonce = "";
int g_nonceCounter = 0;
int64 g_nonceSentAt = 0;
// The server login the nonce was issued for — a change means a new nonce.
string g_nonceServerLogin = "";

// Cached so we print a line only when the server actually changes.
string g_lastLoggedServerLogin = "";

// Whether the floating OnZVoIP window is shown, toggled from the "Plugins"
// menu entry added by RenderMenu() in Interface.as.
bool g_windowOpen = true;

// State pushed by the relay. -1 = not yet received.
int g_statePlayersInRoom = -1;
bool g_stateWebConnected = false;
bool g_stateMicMuted = false;
string g_tcpReadBuf = "";

void Main() {
    print("OnZVoIP: plugin started, Main() running");
    while (true) {
        yield();
        int64 now = Time::Now;

        // IsReady() alone misses a relay restart: the socket can report
        // ready while the peer has actually hung up. IsHungUp() catches that
        // so the plugin reconnects instead of silently sending nothing.
        if (g_socket is null || !g_socket.IsReady() || g_socket.IsHungUp()) {
            g_loggedConnected = false;
            g_authSent = false;    // re-send auth on reconnect (new socket)
            g_nonce = "";          // stale nonce after disconnect
            g_tcpReadBuf = "";
            g_statePlayersInRoom = -1;
            g_stateWebConnected = false;
            g_stateMicMuted = false;
            if (g_authFailed) continue; // stopped — use the Retry button in the widget
            if (now - g_lastConnectAttemptAt < RECONNECT_INTERVAL_MS) continue;
            g_lastConnectAttemptAt = now;
            TryConnect();
            continue;
        }

        if (!g_loggedConnected) {
            print("OnZVoIP: connected to relay at " + S_RelayHost + ":" + S_RelayPort);
            g_loggedConnected = true;
        }

        // Auth must be the first message on the connection: a relay with a
        // configured secret closes the socket on anything else.
        if (!g_authSent) {
            if (S_RelaySecret == "") {
                // Nothing configured on this side. If the relay also has no
                // secret set, it doesn't care what arrives first, so skip
                // straight to sending real data. If the relay does require
                // one, the first nonce/position message will get rejected
                // and the authError check below flags g_authFailed so the
                // widget can prompt for it.
                g_authSent = true;
            } else if (g_authFailed && S_RelaySecret == g_lastAuthFailSecret
                       && (now - g_lastAuthFailAt) < AUTH_RETRY_BACKOFF_MS) {
                // Same secret that already failed, backoff not elapsed yet —
                // skip the HTTPS call this cycle instead of retrying it every
                // RECONNECT_INTERVAL_MS. The socket still cycles below, but
                // /tcp-auth doesn't get hit again until the backoff passes or
                // the player types a different value.
                @g_socket = null;
                continue;
            } else {
                // Exchange the permanent secret for a short-lived, single-use
                // token over HTTPS before writing anything to the plaintext
                // TCP socket — see FetchAuthToken() in Network.as.
                string token = FetchAuthToken();
                if (token == "") {
                    g_authFailed = true;
                    g_lastAuthFailSecret = S_RelaySecret;
                    g_lastAuthFailAt = now;
                    @g_socket = null; // drop and retry via the normal reconnect path
                    continue;
                }
                if (token != "__no_auth__") {
                    // Relay accepted the secret exchange — send the one-time token.
                    string authLine = "{\"type\":\"auth\",\"token\":\"" + EscapeJsonStr(token) + "\"}\n";
                    g_socket.WriteRaw(authLine);
                }
                // token == "__no_auth__": relay has no secret, skip auth message.
                g_authSent = true;
                g_authFailed = false;
            }
        }

        // Read relay → plugin messages. The relay sends newline-delimited JSON:
        // {"type":"authError"} on rejected auth, {"type":"state",...} for
        // periodic state updates. Buffer incomplete lines across
        // yields; discard and reset if the buffer grows beyond 4 KB (guards
        // against a misbehaving relay sending garbage without newlines).
        if (g_socket.IsReady()) {
            string chunk = g_socket.ReadRaw(512);
            if (chunk.Length > 0) {
                g_tcpReadBuf += chunk;
                if (g_tcpReadBuf.Length > 4096) {
                    g_tcpReadBuf = "";
                } else {
                    int nl;
                    while ((nl = g_tcpReadBuf.IndexOf("\n")) >= 0) {
                        string line = g_tcpReadBuf.SubStr(0, nl);
                        g_tcpReadBuf = g_tcpReadBuf.SubStr(nl + 1, g_tcpReadBuf.Length - (nl + 1));
                        line = line.Trim();
                        if (line.Contains("authError")) {
                            g_authFailed = true;
                        } else if (line.Contains("\"state\"")) {
                            Json::Value@ json = Json::Parse(line);
                            if (json !is null) {
                                if (json.HasKey("players")) g_statePlayersInRoom = int(json["players"]);
                                if (json.HasKey("web"))     g_stateWebConnected  = bool(json["web"]);
                                if (json.HasKey("mic"))     g_stateMicMuted       = bool(json["mic"]);
                            }
                        }
                    }
                }
            }
        }

        if (now - g_lastSendAt < SEND_INTERVAL_MS) continue;
        g_lastSendAt = now;

        vec3 pos;
        string login;
        string failReason;
        if (!TryGetLocalPlayerPosition(pos, login, failReason)) {
            if (now - g_lastDiagAt >= DIAG_INTERVAL_MS) {
                g_lastDiagAt = now;
                print("OnZVoIP: not sending yet - " + failReason);
            }
            continue;
        }

        string serverLogin, serverName, serverFail;
        bool onServer = TryGetServerInfo(serverLogin, serverName, serverFail);

        // Log server joins/leaves/switches.
        if (onServer) {
            if (serverLogin != g_lastLoggedServerLogin) {
                print("OnZVoIP: server = login=\"" + serverLogin + "\" name=\"" + serverName + "\"");
                g_lastLoggedServerLogin = serverLogin;
            }
        } else if (g_lastLoggedServerLogin != "") {
            print("OnZVoIP: left server (" + serverFail + ")");
            g_lastLoggedServerLogin = "";
        }

        // Send a fresh nonce when we first connect, when the server changes,
        // or when the TTL is about to expire.
        bool nonceStale = g_nonce == ""
            || serverLogin != g_nonceServerLogin
            || (now - g_nonceSentAt) >= NONCE_REFRESH_MS;
        if (nonceStale && onServer) {
            SendNonce(login, serverLogin, serverName, now);
        } else if (g_nonce == "" && !onServer) {
            // Not on a server yet — send a nonce without one so the URL at
            // least identifies the player (room falls back to the default).
            SendNonce(login, "", "", now);
        }

        // Include the server login (and raw name) so the relay can route
        // this position to the right room; an empty server falls back to
        // the default room for backward compatibility.
        string line = "{\"type\":\"position\",\"pseudo\":\"" + login + "\","
            + "\"server\":\"" + serverLogin + "\","
            + "\"serverName\":\"" + EscapeJsonStr(serverName) + "\","
            + "\"x\":" + FormatFloat(pos.x) + ","
            + "\"y\":" + FormatFloat(pos.y) + ","
            + "\"z\":" + FormatFloat(pos.z) + "}\n";
        if (!g_socket.WriteRaw(line) && now - g_lastDiagAt >= DIAG_INTERVAL_MS) {
            g_lastDiagAt = now;
            print("OnZVoIP: WriteRaw failed | IsReady=" + g_socket.IsReady()
                + " IsHungUp=" + g_socket.IsHungUp());
        }
    }
}
