// OnZVoIP - reports the local player's live position to the OnZVoIP relay,
// so it can be broadcast to other players for proximity voice chat.
// Speaks the same protocol as ../tools/simulate-positions.js: one line of
// JSON per position update, newline-delimited, over a raw TCP socket (no
// extra plugin dependency needed — Net::Socket is available out of the box).
//
// Split across files (OpenPlanet compiles every .as file in the plugin
// folder together as one module, so no includes are needed): Main.as (state
// + main loop), Network.as (relay connection/protocol), Interface.as (ImGui
// window + menu), GameState.as (reading player/server info from the game),
// Strings.as (JSON/Trackmania string helpers), Settings.as (user-configurable
// options).

// How often we LOOK at the car. Cheap (one game-state read, no socket write),
// and the faster we look, the sooner a sudden move can be reported.
const int SAMPLE_INTERVAL_MS = 100;
// How often we actually put a position on the wire while the car is moving.
// This is the rate the whole system was tuned around; the browser smooths
// between packets (extrapolation), so it is a floor, not a quality knob.
const int SEND_INTERVAL_MOVING_MS = 200;
// Parked in a menu, at the start line, or spectating: nothing to describe, so
// stop paying the relay's fan-out for it. Still frequent enough to stay well
// inside the browser's 3 s "stale" mute, so a stationary player never fades.
const int SEND_INTERVAL_IDLE_MS = 1000;
// Under this, the car has not really moved - engine idle, physics jitter.
const float POSITION_IDLE_EPSILON_M = 0.25f;
// A jump this big is a respawn, a checkpoint restart or a teleport. It goes out
// on the next sample without waiting for the cadence: this is the one case
// where the browser's extrapolation would be actively wrong.
const float POSITION_JUMP_M = 8.0f;
// Turning on the spot moves nobody but rotates everyone's stereo image, so a
// heading change counts as movement even at a standstill.
const float HEADING_EPSILON = 0.08f;
const int RECONNECT_INTERVAL_MS = 2000;
const int DIAG_INTERVAL_MS = 3000;
// Refresh the nonce before the relay's 12-minute TTL expires.
const int NONCE_REFRESH_MS = 9 * 60 * 1000;
// While a secret keeps failing, retry the HTTPS token exchange at most this
// often instead of every RECONNECT_INTERVAL_MS — the TCP socket still cycles
// (harmless), but /tcp-auth stops getting hammered while the player figures
// out the right value. A changed secret retries immediately regardless.
const int AUTH_RETRY_BACKOFF_MS = 10000;

Net::Socket@ g_socket = null;
int64 g_lastSampleAt = 0;
// The last position/heading we actually put on the wire, so the next sample can
// tell "moved" from "parked" (see SEND_INTERVAL_IDLE_MS).
vec3 g_lastSentPos = vec3(0, 0, 0);
float g_lastSentFx = 0.0f;
float g_lastSentFz = 0.0f;
bool g_hasLastSent = false;
int64 g_lastConnectAttemptAt = 0;
int64 g_lastDiagAt = 0;
bool g_loggedConnected = false;
bool g_authSent = false;
// Set when the relay rejects our auth (wrong/missing secret) so the widget
// can tell the player "this relay needs a token" instead of just showing
// "connecting..." forever.
bool g_authFailed = false;
// The secret and timestamp of the last failed auth attempt, so a still-wrong
// secret doesn't retry the HTTPS token exchange every reconnect — see
// AUTH_RETRY_BACKOFF_MS. Editing the secret field resets g_authFailed
// (Interface.as), which bypasses this and retries right away.
string g_lastAuthFailSecret = "";
int64 g_lastAuthFailAt = 0;

// One-time nonce generated by the plugin, sent to the relay over TCP and
// embedded in the "Copy URL" link. The relay exchanges it for a JWT already
// bound to the right room, so the player never has to type a login in.
string g_nonce = "";
int64 g_nonceSentAt = 0;
// The server login the nonce was issued for — a change means a new nonce.
string g_nonceServerLogin = "";

// Cached so we print a line only when the server actually changes.
string g_lastLoggedServerLogin = "";

// Whether the floating OnZVoIP window is shown, toggled from the "Plugins"
// menu entry added by RenderMenu() in Interface.as.
bool g_windowOpen = true;

// State pushed by the relay. -1 = not yet received.
int g_statePlayersInRoom = -1;
bool g_stateWebConnected = false;
bool g_stateMicActive = false;
string g_tcpReadBuf = "";

// Raised by the widget's Retry/Reconnect buttons. The main loop owns the
// socket, so the button only asks: tearing the connection down from inside a
// UI callback would drop it halfway through an iteration of the loop below.
bool g_forceReconnect = false;

// Diagnostics behind "Advanced" in the widget: when a position last actually
// went out, and — while it isn't going out — why. Cleared on every successful
// send so a stale reason can never sit there looking like a live one.
int64 g_lastPositionOkAt = 0;
string g_lastSendFail = "";

void Main() {
    print("OnZVoIP: plugin started, Main() running");
    while (true) {
        yield();
        int64 now = Time::Now;

        // The widget asked for a fresh connection. Clearing g_authFailed is
        // what makes this useful after a corrected secret: the auth backoff
        // below only holds while that flag is set, so the retry goes out on
        // this very iteration instead of waiting AUTH_RETRY_BACKOFF_MS. Zeroing
        // the attempt timestamp likewise skips RECONNECT_INTERVAL_MS, so the
        // click feels immediate rather than up to two seconds late.
        if (g_forceReconnect) {
            g_forceReconnect = false;
            g_authFailed = false;
            g_lastConnectAttemptAt = 0;
            @g_socket = null;
        }

        // IsReady() alone misses a relay restart: the socket can report
        // ready while the peer has actually hung up. IsHungUp() catches that
        // so the plugin reconnects instead of silently sending nothing.
        if (g_socket is null || !g_socket.IsReady() || g_socket.IsHungUp()) {
            g_loggedConnected = false;
            g_authSent = false;    // re-send auth on reconnect (new socket)
            g_nonce = "";          // stale nonce after disconnect
            g_tcpReadBuf = "";
            g_statePlayersInRoom = -1;
            g_stateWebConnected = false;
            g_stateMicActive = false;
            if (g_authFailed) continue; // stopped — use the Retry button in the widget
            if (now - g_lastConnectAttemptAt < RECONNECT_INTERVAL_MS) continue;
            g_lastConnectAttemptAt = now;
            TryConnect();
            continue;
        }

        if (!g_loggedConnected) {
            print("OnZVoIP: connected to relay at " + S_RelayHost + ":" + S_RelayPort);
            g_loggedConnected = true;
        }

        // Auth must be the first message on the connection: a relay with a
        // configured secret closes the socket on anything else.
        if (!g_authSent) {
            if (S_RelaySecret == "") {
                // Nothing configured on this side. If the relay also has no
                // secret set, it doesn't care what arrives first, so skip
                // straight to sending real data. If the relay does require
                // one, the first nonce/position message will get rejected
                // and the authError check below flags g_authFailed so the
                // widget can prompt for it.
                g_authSent = true;
            } else if (g_authFailed && S_RelaySecret == g_lastAuthFailSecret
                       && (now - g_lastAuthFailAt) < AUTH_RETRY_BACKOFF_MS) {
                // Same secret that already failed, backoff not elapsed yet —
                // skip the HTTPS call this cycle instead of retrying it every
                // RECONNECT_INTERVAL_MS. The socket still cycles below, but
                // /tcp-auth doesn't get hit again until the backoff passes or
                // the player types a different value.
                @g_socket = null;
                continue;
            } else {
                // Exchange the permanent secret for a short-lived, single-use
                // token over HTTPS before writing anything to the plaintext
                // TCP socket — see FetchAuthToken() in Network.as.
                string token = FetchAuthToken();
                if (token == "") {
                    g_authFailed = true;
                    g_lastAuthFailSecret = S_RelaySecret;
                    g_lastAuthFailAt = now;
                    @g_socket = null; // drop and retry via the normal reconnect path
                    continue;
                }
                if (token != "__no_auth__") {
                    // Relay accepted the secret exchange — send the one-time token.
                    string authLine = "{\"type\":\"auth\",\"token\":\"" + EscapeJsonStr(token) + "\"}\n";
                    g_socket.WriteRaw(authLine);
                }
                // token == "__no_auth__": relay has no secret, skip auth message.
                g_authSent = true;
                g_authFailed = false;
            }
        }

        // Read relay → plugin messages. The relay sends newline-delimited JSON:
        // {"type":"authError"} on rejected auth, {"type":"nonceUsed"} when a
        // browser has spent our link, {"type":"state",...} for periodic state
        // updates. Buffer incomplete lines across
        // yields; discard and reset if the buffer grows beyond 4 KB (guards
        // against a misbehaving relay sending garbage without newlines).
        if (g_socket.IsReady()) {
            string chunk = g_socket.ReadRaw(512);
            if (chunk.Length > 0) {
                g_tcpReadBuf += chunk;
                if (g_tcpReadBuf.Length > 4096) {
                    g_tcpReadBuf = "";
                } else {
                    int nl;
                    while ((nl = g_tcpReadBuf.IndexOf("\n")) >= 0) {
                        string line = g_tcpReadBuf.SubStr(0, nl);
                        g_tcpReadBuf = g_tcpReadBuf.SubStr(nl + 1, g_tcpReadBuf.Length - (nl + 1));
                        line = line.Trim();
                        if (line.Contains("authError")) {
                            g_authFailed = true;
                        } else if (line.Contains("nonceUsed")) {
                            // A browser just spent our link, so the URL on
                            // screen is dead. Blanking it makes the loop below
                            // mint another within 200 ms — otherwise the player
                            // would have to wait out NONCE_REFRESH_MS (or
                            // reload the plugin) before the link worked again.
                            g_nonce = "";
                        } else if (line.Contains("\"state\"")) {
                            Json::Value@ json = Json::Parse(line);
                            if (json !is null) {
                                if (json.HasKey("players")) g_statePlayersInRoom = int(json["players"]);
                                if (json.HasKey("web"))     g_stateWebConnected  = bool(json["web"]);
                                // "mic" is true when the microphone is OPEN,
                                // not when it is muted. Reading it as "muted"
                                // is what made the widget say the opposite of
                                // the truth, so the name here says which it is.
                                if (json.HasKey("mic"))     g_stateMicActive     = bool(json["mic"]);
                            }
                        }
                    }
                }
            }
        }

        if (now - g_lastSampleAt < SAMPLE_INTERVAL_MS) continue;
        g_lastSampleAt = now;

        vec3 pos;
        vec3 aimDir;
        bool hasAim;
        string login;
        string failReason;
        if (!TryGetLocalPlayerPosition(pos, aimDir, hasAim, login, failReason)) {
            g_lastSendFail = failReason;
            if (now - g_lastDiagAt >= DIAG_INTERVAL_MS) {
                g_lastDiagAt = now;
                print("OnZVoIP: not sending yet - " + failReason);
            }
            continue;
        }

        string serverLogin, serverName, serverFail;
        bool onServer = TryGetServerInfo(serverLogin, serverName, serverFail);

        // Log server joins/leaves/switches.
        if (onServer) {
            if (serverLogin != g_lastLoggedServerLogin) {
                print("OnZVoIP: server = login=\"" + serverLogin + "\" name=\"" + serverName + "\"");
                g_lastLoggedServerLogin = serverLogin;
            }
        } else if (g_lastLoggedServerLogin != "") {
            print("OnZVoIP: left server (" + serverFail + ")");
            g_lastLoggedServerLogin = "";
        }

        // Send a fresh nonce when we first connect, when the server changes,
        // or when the TTL is about to expire.
        bool nonceStale = g_nonce == ""
            || serverLogin != g_nonceServerLogin
            || (now - g_nonceSentAt) >= NONCE_REFRESH_MS;
        if (nonceStale && onServer) {
            SendNonce(login, serverLogin, serverName, now);
        } else if (g_nonce == "" && !onServer) {
            // Not on a server yet — send a nonce without one so the URL at
            // least identifies the player (room falls back to the default).
            SendNonce(login, "", "", now);
        }

        // Which way the car points, so the browser can rotate the stereo image
        // and the radar with it. Only the horizontal part goes out: driving up a
        // ramp tilts AimDirection, and the tilt would otherwise shrink the
        // left/right component for no reason. Sent as a vector rather than an
        // angle so neither side has to agree on where zero points. Left out
        // entirely when unavailable — the browser then keeps the world-space
        // behaviour instead of being handed a heading of (0, 0).
        string headingPart = "";
        if (hasAim) {
            headingPart = ",\"fx\":" + FormatFloat(aimDir.x) + ",\"fz\":" + FormatFloat(aimDir.z);
        }

        // Adaptive cadence: a position is only worth sending if it says
        // something the last one did not. A car at racing speed still goes out
        // every SEND_INTERVAL_MOVING_MS; a car parked in a menu drops to the
        // idle heartbeat, which is what keeps the relay's fan-out (one message
        // per sender per listener) from being paid for players who are not
        // moving. The browser extrapolates between packets, so slowing down
        // here does not make anyone's voice step.
        float fx = hasAim ? aimDir.x : 0.0f;
        float fz = hasAim ? aimDir.z : 0.0f;
        float dx = pos.x - g_lastSentPos.x;
        float dy = pos.y - g_lastSentPos.y;
        float dz = pos.z - g_lastSentPos.z;
        float moved = Math::Sqrt(dx * dx + dy * dy + dz * dz);
        float turned = Math::Abs(fx - g_lastSentFx) + Math::Abs(fz - g_lastSentFz);
        int64 sinceSent = now - g_lastPositionOkAt;
        bool due = !g_hasLastSent
            || moved >= POSITION_JUMP_M
            || sinceSent >= SEND_INTERVAL_IDLE_MS
            || ((moved >= POSITION_IDLE_EPSILON_M || turned >= HEADING_EPSILON)
                && sinceSent >= SEND_INTERVAL_MOVING_MS);
        if (!due) continue;

        // Include the server login (and raw name) so the relay can route
        // this position to the right room; an empty server falls back to
        // the default room for backward compatibility.
        string line = "{\"type\":\"position\",\"pseudo\":\"" + login + "\","
            + "\"server\":\"" + serverLogin + "\","
            + "\"serverName\":\"" + EscapeJsonStr(serverName) + "\","
            + "\"x\":" + FormatFloat(pos.x) + ","
            + "\"y\":" + FormatFloat(pos.y) + ","
            + "\"z\":" + FormatFloat(pos.z) + headingPart + "}\n";
        if (!g_socket.WriteRaw(line)) {
            g_lastSendFail = "socket write failed";
            if (now - g_lastDiagAt >= DIAG_INTERVAL_MS) {
                g_lastDiagAt = now;
                print("OnZVoIP: WriteRaw failed | IsReady=" + g_socket.IsReady()
                    + " IsHungUp=" + g_socket.IsHungUp());
            }
        } else {
            g_lastPositionOkAt = now;
            g_lastSendFail = "";
            // Only a position that made it out becomes the reference: if the
            // write failed, the next sample must still compare against the last
            // thing the relay actually knows about us.
            g_lastSentPos = pos;
            g_lastSentFx = fx;
            g_lastSentFz = fz;
            g_hasLastSent = true;
        }
    }
}
